name: Build

on:
 push:
  paths:
  - '.github/workflows/Build.yml'
  - 'src/**.c'
  - 'src/**.h'
  - '**/CMakeLists.txt'
 pull_request:
  paths:
  - '.github/workflows/Build.yml'
  - 'src/**.c'
  - 'src/**.h'
  - '**/CMakeLists.txt'

defaults:
 run:
  shell: bash

jobs:

 build-windows:
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: Prepare
    run:  cmake -B Build -A Win32

  - name: Release build
    run:  cmake --build Build --config Release

  - name: Artifact
    uses: actions/upload-artifact@v3
    with:
     name: fallout2-ce
     path: |
      Build/*/fallout2-ce.exe
     retention-days: 7

 build-linux32:
  runs-on: ubuntu-22.04
  steps:

  - name: Clone
    uses: actions/checkout@v2

  - name: Install dependencies
    run: sudo apt-get install g++-multilib libsdl2-dev libsdl2-2.0-0:i386 

  - name: Prepare
    run: cmake -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32" -B build

  - name: Release build
    run: cmake --build build --config Release
